### ISSUE TITLE
Branching

### ISSUE THREAD

**Issue by Malix-Labs** [scratch-for-discord/scratch-for-discord#17]
## Subject

[Web-Application Frontend Branches](https://github.com/scratch-for-discord/Web-Application_Frontend/branches)

## Task

- [x] Delete [`v2-base-prototype`](https://github.com/scratch-for-discord/Web-Application_Frontend/tree/v2-base-prototype)
- [x] Delete [`v2-prototype`](https://github.com/scratch-for-discord/Web-Application_Frontend/tree/v2-prototype)
- [x] Delete [`v2-OAuth2-UI`](https://github.com/scratch-for-discord/Web-Application_Frontend/tree/v2-OAuth2-UI)
- [x] Delete [`469_beta`](https://github.com/scratch-for-discord/Web-Application_Frontend/tree/469_beta)
- [x] Rename [`469-djs-v14`](https://github.com/scratch-for-discord/Web-Application_Frontend/tree/469-djs-v14) as "[`update/toolbox/discord.js/14.0.0`](https://github.com/scratch-for-discord/Web-Application_Frontend/tree/update/toolbox/discord.js/14.0.0)"
- [x] Rename [`v3-react`](https://github.com/scratch-for-discord/Web-Application_Frontend/tree/v3-react) as "[`release/3/master`](https://github.com/scratch-for-discord/Web-Application_Frontend/tree/release/3/master)"
- [x] Merge [`469_main`](https://github.com/scratch-for-discord/Web-Application_Frontend/tree/469_main) into [`master`](https://github.com/scratch-for-discord/Web-Application_Frontend), then delete it
- [x] Create "[`develop`](https://github.com/scratch-for-discord/Web-Application_Frontend/tree/develop)" from [`master`](https://github.com/scratch-for-discord/Web-Application_Frontend)
- [x] Create [`release/3/develop`](https://github.com/scratch-for-discord/Web-Application_Frontend/tree/release/3/develop) from [`release/3/master`](https://github.com/scratch-for-discord/Web-Application_Frontend/tree/release/3/master)
- [x] [Protect `master`](https://github.com/scratch-for-discord/Web-Application_Frontend/settings/branch_protection_rules/29511987)
- [x] [Protect `develop`](https://github.com/scratch-for-discord/Web-Application_Frontend/settings/branch_protection_rules/29511991)
- [x] [Protect `release/*/master`](https://github.com/scratch-for-discord/Web-Application_Frontend/settings/branch_protection_rules/29511304)
- [x] [Protect `release/*/develop`](https://github.com/scratch-for-discord/Web-Application_Frontend/settings/branch_protection_rules/29511781)
- [x] Make the [Developer's Documentation﹣Git](https://github.com/scratch-for-discord/Web-Application_Frontend/wiki/Git)

## Changes

- **[`469_main`](https://github.com/scratch-for-discord/Web-Application_Frontend/tree/469_main)** : merged into **[`master`](https://github.com/scratch-for-discord/Web-Application_Frontend)**
- **[`v3-react`](https://github.com/scratch-for-discord/Web-Application_Frontend/tree/v3-react)** : renamed as "**[`release/3/master`](https://github.com/scratch-for-discord/Web-Application_Frontend/tree/release/3/master)**"
- **[`469-djs-v14`](https://github.com/scratch-for-discord/Web-Application_Frontend/tree/469-djs-v14)** : renamed as "**[`update/toolbox/discord.js/14.0.0`](https://github.com/scratch-for-discord/Web-Application_Frontend/tree/update/toolbox/discord.js/14.0.0)**"
- **[`469_beta`](https://github.com/scratch-for-discord/Web-Application_Frontend/tree/469_beta)** : deleted
- **[`v2-OAuth2-UI`](https://github.com/scratch-for-discord/Web-Application_Frontend/tree/v2-OAuth2-UI)** : deleted
- **[`v2-prototype`](https://github.com/scratch-for-discord/Web-Application_Frontend/tree/v2-prototype)** : deleted
- **[`v2-base-prototype`](https://github.com/scratch-for-discord/Web-Application_Frontend/tree/v2-base-prototype)** : deleted

## Result

- **[`master`](https://github.com/scratch-for-discord/Web-Application_Frontend)** (protected﹣undeletable, requires PR) : deployed main code
- **[`develop`](https://github.com/scratch-for-discord/Web-Application_Frontend/tree/develop)** (protected﹣undeletable) : main development branch
- **[`update/toolbox/discord.js/14.0.0`](https://github.com/scratch-for-discord/Web-Application_Frontend/tree/update/toolbox/discord.js/14.0.0)** : development branch of the update of the toolbox about [discord.js v14.0.0](https://github.com/discordjs/discord.js/releases/tag/14.5.0)
- **[`release/3/master`](https://github.com/scratch-for-discord/Web-Application_Frontend/tree/release/3/master)** (protected﹣requires PR) : production code of v3
- **[`release/3/develop`](https://github.com/scratch-for-discord/Web-Application_Frontend/tree/release/3/develop)** : main development branch of v3

## Documentation

- [Developer's Documentation﹣Git](https://github.com/scratch-for-discord/Web-Application_Frontend/wiki/Git)
