### ISSUE TITLE
Drop-down saving

### ISSUE THREAD

**Issue by Malix-Labs** [scratch-for-discord/scratch-for-discord#25]
## Behavior

Drop-down not saving upon options update

## Problem Source

_Identified_

Multiline export with simple arrays

## Solution

Change multiline export with simple arrays by multiline export with switch-case

## Documentation

[Documentation](https://github.com/scratch-for-discord/Web-Application_Frontend/wiki/Toolbox-Blocks-Guidelines)

## Tasks

- [ ] Identify the source and the condition for this behavior to happen (did by @JeremyGamer13)
- [x] Find a solution (did by @JeremyGamer13)
- [x] Make a developer documentation (on [this repository wiki](https://github.com/scratch-for-discord/Web-Application_Frontend/wiki)) (did by @Malix-Off and @RedMan13)

## Links

- **[Official Discord Thread](https://discord.com/channels/932651844344373278/1012003677575319714)** : https://discord.com/channels/932651844344373278/1012003677575319714

**Comment by RedMan13** [comment]
helloooooooo
