### ISSUE TITLE
Comply with Gitbook's Open-Sourcing Terms

### ISSUE THREAD

**Issue by Malix-Labs** [scratch-for-discord/scratch-for-discord#59]
## Tasks

- [x] Exists on GitHub or GitLab
- [x] Is not just an empty repository with nothing to show
- [x] Is not just a fork with no activity of its own
- [x] Has a README.md file that clearly explains what the software is about
- [x] Has a CONTRIBUTING.md file that explains how to contribute
- [x] Has a LICENSE file with [a valid OSS license](https://choosealicense.com/)
- [ ] Has a CODE_OF_CONDUCT.md
- [x] Makes it easy for others [to contribute](https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/finding-ways-to-contribute-to-open-source-on-github#finding-good-first-issues)

## Links

- **[GitBook﹣Documentation︱Plans﹣Non-profit & Open-source](https://docs.gitbook.com/billing-and-admin/plans/non-profit-open-source-plan/)**
- **[GitBook﹣Showcase](https://www.gitbook.com/)**
- **[GitBook﹣App](https://app.gitbook.com/)**
- **[S4D︱GitBook](https://app.gitbook.com/o/X1rAxqUkZ7dvd6GQon4C/)**
- **[S4D︱GitBook﹣Plans](https://app.gitbook.com/o/X1rAxqUkZ7dvd6GQon4C/settings/plans/)**
